name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libspatialindex-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/cpu
          pip install dgl -f https://data.dgl.ai/wheels/torch-2.3/cpu/repo.html
          pip install torchdata==0.9.0
          pip install -r requirements.txt
          pip freeze
          ls -la /opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/dgl/graphbolt/
      - name: Install this package
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          pytest
